### PR TITLE
added linux notification

### PR DESCRIPTION
**Pull request by basaran**
added "m" to string as well. Could you see if the os_check works for you on mac and merge if all is well?

### CODE REVIEW

**Comment by olimorris** [comment]
Amazing!! Thank you so much. I shall test out later today.

**Comment by basaran** [comment]
Hello, it turns out tmux has a nice command prompt. I added additional method to set the timer manually. Should probably add some validation there perhaps. Also, I wasn't sure if it should restart an existing timer. Please create an issue if you would like to discuss.

**Comment by olimorris** [comment]
Can confirm that it works on Mac perfectly.

Regarding the custom pomodoro timer. I ❤️ the idea. Fully onboard. Only request...once you enter a value in the command prompt, can you trigger the countdown? I love that it stores the input for future pomodoros though.

**Comment by basaran** [comment]
I looked more into this, I think it's best to avoid the task name. A pomodoro timer is not a task manager, for that we have orgmode :)

**Comment by olimorris** [comment]
All really good points. My thoughts are that we run the risk of making this really complicated. Your initial idea of customising the timer is great and the API can be called out in the README to make it clear to all users.

I'm keen to merge this into main, as-is. What are your thoughts?

**Comment by mskelton** [comment]
This seems to have broken sound on macOS due to these lines.

https://github.com/olimorris/tmux-pomodoro-plus/pull/2/files#diff-49376947ccc1be4101aa3ff278c29ca8d4e0809d5cc6e1e9102daf15b8e8f4bdR80-R85

It checks if the sound is `'on'` but then uses that as the sounds name but `on` is not a sound name.

**Pull request merged**
